package org.example.smartagriculture.model;

import java.util.Date;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_device.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_device.device_name
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_device.create_at
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_device.master
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private Integer master;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_device.id
     *
     * @return the value of smart_device.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_device.id
     *
     * @param id the value for smart_device.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_device.device_name
     *
     * @return the value of smart_device.device_name
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_device.device_name
     *
     * @param deviceName the value for smart_device.device_name
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_device.create_at
     *
     * @return the value of smart_device.create_at
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_device.create_at
     *
     * @param createAt the value for smart_device.create_at
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_device.master
     *
     * @return the value of smart_device.master
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public Integer getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_device.master
     *
     * @param master the value for smart_device.master
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setMaster(Integer master) {
        this.master = master;
    }
}