package org.example.smartagriculture.model;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.title
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.file_url
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.creat_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private Integer creatUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.update_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.delete_flag
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_news.content
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.id
     *
     * @return the value of smart_news.id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.id
     *
     * @param id the value for smart_news.id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.title
     *
     * @return the value of smart_news.title
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.title
     *
     * @param title the value for smart_news.title
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.file_url
     *
     * @return the value of smart_news.file_url
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.file_url
     *
     * @param fileUrl the value for smart_news.file_url
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.creat_user_id
     *
     * @return the value of smart_news.creat_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public Integer getCreatUserId() {
        return creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.creat_user_id
     *
     * @param creatUserId the value for smart_news.creat_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setCreatUserId(Integer creatUserId) {
        this.creatUserId = creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.update_user_id
     *
     * @return the value of smart_news.update_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.update_user_id
     *
     * @param updateUserId the value for smart_news.update_user_id
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.delete_flag
     *
     * @return the value of smart_news.delete_flag
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.delete_flag
     *
     * @param deleteFlag the value for smart_news.delete_flag
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_news.content
     *
     * @return the value of smart_news.content
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_news.content
     *
     * @param content the value for smart_news.content
     *
     * @mbg.generated Fri Jul 12 10:35:36 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}