package org.example.smartagriculture.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.username
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.password
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.nickname
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.email
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_user.phone
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.id
     *
     * @return the value of smart_user.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.id
     *
     * @param id the value for smart_user.id
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.username
     *
     * @return the value of smart_user.username
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.username
     *
     * @param username the value for smart_user.username
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.password
     *
     * @return the value of smart_user.password
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.password
     *
     * @param password the value for smart_user.password
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.nickname
     *
     * @return the value of smart_user.nickname
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.nickname
     *
     * @param nickname the value for smart_user.nickname
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.email
     *
     * @return the value of smart_user.email
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.email
     *
     * @param email the value for smart_user.email
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_user.phone
     *
     * @return the value of smart_user.phone
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_user.phone
     *
     * @param phone the value for smart_user.phone
     *
     * @mbg.generated Tue Jul 09 21:39:03 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}