package org.example.smartagriculture.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.smartagriculture.model.Device;
import org.example.smartagriculture.model.DeviceExample;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    long countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_device
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByPrimaryKey(Device record);
}