package org.example.smartagriculture.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.smartagriculture.model.News;
import org.example.smartagriculture.model.NewsExample;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    long countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    List<News> selectByExampleWithBLOBs(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_news
     *
     * @mbg.generated Fri Jul 12 10:38:30 CST 2024
     */
    int updateByPrimaryKey(News record);

    List<News> findAll();
}